In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
import yaml
import numpy as np
from pathlib import Path

# Add project root to Python path
sys.path.append(os.path.abspath(".."))
sys.path.append("../")
sys.path.append(str(Path().resolve().parent))


from src.utils import ROOT_DIR, RAW_DATA_DIR, PROCESSED_DATA_DIR, CONFIG_PATH
from src.preprocessing import (
    load_hex_lines,
    convert_dataset,
    group_sequences,
    train_test_split_sequences
)

from src.generate_prng_data import (
    generate_cs_prng_hex, 
    generate_bit_array_npy
)


In [3]:
with open(CONFIG_PATH, "r") as f:
    config = yaml.safe_load(f)

In [4]:
# Access to raw data

#trng_file = get_raw_data_path("trng_hex.txt")
#prng_embedded_file = get_raw_data_path("prng_embedded.txt")
#prng_python_file = get_raw_data_path("prng_python.txt")

trng_file = RAW_DATA_DIR/config["data"]["raw"]["trng"]
prng_embedded_file = RAW_DATA_DIR/config["data"]["raw"]["prng_embedded"]
prng_python_file = PROCESSED_DATA_DIR/config["data"]["processed"]["prng_python"]
cs_prng_python_file = RAW_DATA_DIR/config["data"]["raw"]["cs_prng_python"]

In [5]:
# Load hex data
trng_hex = load_hex_lines(trng_file)
prng_embedded_hex = load_hex_lines(prng_embedded_file)
# Uncomment the next line if you would like to generate new set of numbers for the cs_prng_python raw data
#cs_prng_python_hex = generate_cs_prng_hex(cs_prng_python_file)
cs_prng_python_hex = load_hex_lines(cs_prng_python_file)

In [6]:
# Generate TRNG data with python random library
prng_python_data = generate_bit_array_npy(prng_python_file)
print(prng_python_data[:1])
print(len(prng_python_data))

[[0 0 1 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 1
  0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 1
  0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 1 1 0 0 0 1 1 1 1 0 1 1 0 1 0 0 0 1
  0 1 0 0 0 0 0 0 1 0 1 1 1 1 1 1 1 0 1 0]]
7812


In [7]:
# Convert whole dataset
# Convert hex values to bits
trng_data = convert_dataset(trng_hex)
prng_embedded_data = convert_dataset(prng_embedded_hex)
cs_prng_python_data = convert_dataset(cs_prng_python_hex)
print(trng_data[:1])
print(len(trng_data))
print(prng_embedded_data[:1])
print(len(prng_embedded_data))
print(cs_prng_python_data[:1])
print(len(cs_prng_python_data))

[[1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0
  0 1 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0
  0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 1 0 1 0 0 0 0 0 0
  1 1 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1]]
14997
[[1 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 0 0
  1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0
  1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 1 1 1 0 0 1 1 0 1 0 0]]
40500
[[0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1
  1 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 1 1 0 0 0 0 1
  1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 0 0 1
  0 1 1 0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0]]
10000


In [11]:
# Grouping the bits in chunks with size "group_size". Default 1024 bits per each group.
group_size = config["preprocessing"]["group_size"]

trng_grouped = group_sequences(trng_data, group_size)
prng_embedded_grouped = group_sequences(prng_embedded_data, group_size)
prng_python_grouped = group_sequences(prng_python_data, group_size)
cs_prng_python_grouped = group_sequences(cs_prng_python_data, group_size)
print(len(trng_grouped))
print(len(trng_grouped[1]))
print(trng_grouped[:1])
print(len(prng_embedded_grouped))
print(len(prng_embedded_grouped[1]))
print(prng_embedded_grouped[:1])
print(len(prng_python_grouped))
print(len(prng_python_grouped[1]))
print(prng_python_grouped[:1])
print(len(cs_prng_python_grouped))
print(len(cs_prng_python_grouped[1]))
print(cs_prng_python_grouped[:1])


1874
1024
[[1 0 0 ... 0 0 1]]
5062
1024
[[1 0 1 ... 0 0 1]]
976
1024
[[0 0 1 ... 0 1 1]]
1250
1024
[[0 1 0 ... 0 1 1]]


In [9]:
np.save(PROCESSED_DATA_DIR/config["data"]["processed"]["trng"], trng_grouped)
np.save(PROCESSED_DATA_DIR/config["data"]["processed"]["prng_embedded"], prng_embedded_grouped)
np.save(PROCESSED_DATA_DIR/config["data"]["processed"]["prng_python"], prng_python_grouped)
np.save(PROCESSED_DATA_DIR/config["data"]["processed"]["cs_prng_python"], cs_prng_python_grouped)